import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./context/stateContext";
import ResponsiveAppBar from "@/components/Nav";
import { Suspense } from 'react';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`} style={{ height: "100vh" }}>
        <UserProvider>
          <Suspense>
            <ResponsiveAppBar />
            {children}
          </Suspense>
        </UserProvider>
      </body>
    </html >
  );
}
