/**
 * lib/stepVideos.js — per-mastery-step follow-along videos for the Foundation programs.
 *
 * AWS served each mastery step its own follow-along (tag 3, "gbpro") video — the one whose
 * weekNum matches the step's weekNum. programCurricula.json only stores the step-1 video,
 * so members were stuck on it. data/workout/programStepVideos.json holds the full map
 * (generated by /var/www/Work/Gymfit/claudeTools/buildProgramStepVideos.mjs from the
 * courses RDS backup, cross-checked against JW titles, every id HEAD-checked in Blob).
 */
import stepVideoMap from "@/data/workout/programStepVideos.json";

// exerciseId -> { image, steps }. Exercise ids are unique across the three Foundation
// courses; the image check below guards against ever applying another exercise's video.
const BY_EXERCISE = new Map();
for (const [courseId, exercises] of Object.entries(stepVideoMap)) {
    if (courseId.startsWith('_')) continue;
    for (const [exerciseId, entry] of Object.entries(exercises)) BY_EXERCISE.set(Number(exerciseId), entry);
}

/** The follow-along video for (prog, stepNo), or null when there is no mapping. */
export function stepVideoFor(prog, stepNo) {
    const entry = BY_EXERCISE.get(Number(prog?.exerciseId));
    if (!entry || entry.image !== prog.image) return null;
    return entry.steps[String(stepNo)] || null;
}

/**
 * Return workoutInfo with every tag-3 follow-along video swapped for the member's step.
 * Mobility / technical-tip / strength-demo videos are untouched; so is anything unmapped.
 */
export function withStepVideos(workoutInfo, prog, stepNo) {
    const sv = stepVideoFor(prog, stepNo);
    if (!workoutInfo || !sv) return workoutInfo;
    const out = { ...workoutInfo };
    for (const key of Object.keys(out)) {
        const block = out[key];
        if (!block?.videos?.some(v => v.tag === 3)) continue;
        out[key] = {
            ...block,
            videos: block.videos.map(v => (v.tag === 3 ? { ...v, videoName: sv.videoName, weekNum: sv.weekNum } : v)),
        };
    }
    return out;
}
